### ISSUE TITLE
Hope for the code release

### ISSUE THREAD

**Issue by CHNxindong** [Boyiliee/3DHM#1]
Great work! Hope for the code release.

**Comment by junwenxiong** [comment]
When will the code be released?

**Comment by Boyiliee** [comment]
Hi @junwenxiong, thanks for your interest in 3DHM! 
We are currently preparing the material and will furnish updated information as soon as it is ready!

**Comment by gitPZH** [comment]
When will the code be uploaded?

**Comment by gitPZH** [comment]
@Boyiliee
