### ISSUE TITLE
Weird results

### ISSUE THREAD

**Issue by Turlan** [Boyiliee/3DHM#3]
Could you show the results of human motion without video editing? Such edited movements with [sudden changes](https://boyiliee.github.io/3DHM.github.io/static/videos/test4_27.mp4) are very annoying to watch. A good example is [Animate Anyone](https://humanaigc.github.io/animate-anyone/).

**Comment by Boyiliee** [comment]
Dear @Turlan , thanks for your note! We will try to improve it in the future.
